# Generated by Django 5.0.7 on 2025-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_is_approved_customuser_is_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
    ]
