# Generated by Django 5.0.7 on 2025-05-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
