# Generated by Django 5.0.7 on 2025-05-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agents', to='app.hub'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='vehicle_number',
            field=models.CharField(max_length=50),
        ),
    ]
