# Generated by Django 5.0.7 on 2025-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_deliveryagent_hub_alter_deliveryagent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hub',
            field=models.BooleanField(default=False),
        ),
    ]
