# Generated by Django 5.0.7 on 2025-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customuser_is_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_branch',
            field=models.BooleanField(default=False),
        ),
    ]
