# Generated by Django 5.0.7 on 2025-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_customuser_is_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_agent',
            field=models.BooleanField(default=False),
        ),
    ]
