# Generated by Django 5.0.7 on 2025-05-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_order_branch_hub_order_delivery_agent_order_main_hub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='branch_hub',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='main_hub',
        ),
        migrations.RemoveField(
            model_name='orderstatusupdate',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='assigned_to_agent',
        ),
        migrations.RemoveField(
            model_name='orderassignment',
            name='assigned_to_hub',
        ),
        migrations.RemoveField(
            model_name='orderstatusupdate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='location',
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAssignment',
        ),
        migrations.DeleteModel(
            name='OrderStatusUpdate',
        ),
    ]
