# Generated by Django 5.0.7 on 2025-05-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_order_branch_hub_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('status', models.CharField(default='At Hub', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.branch')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hub')),
            ],
        ),
    ]
