# Generated by Django 5.0.7 on 2025-05-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hub'),
        ),
    ]
