# Generated by Django 5.2.1 on 2025-05-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_customuser_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parcel'),
        ),
    ]
