# Generated by Django 5.2.1 on 2025-05-29 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_purchase_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.deliveryagent'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('At Hub', 'At Hub'), ('Assigned to Branch', 'Assigned to Branch'), ('Assigned to Agent', 'Assigned to Agent'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='At Hub', max_length=50),
        ),
    ]
