# Generated by Django 5.2.1 on 2025-05-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_parcel_assigned_agent_alter_parcel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='parcel',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='At Hub', max_length=50),
        ),
    ]
