# Generated by Django 5.2.1 on 2025-05-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_parcel_assigned_agent_remove_purchase_parcel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.branch'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='assigned_delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.deliveryagent'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='parcel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parcel'),
        ),
    ]
