# Generated by Django 5.2.1 on 2025-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_purchase_assigned_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
