# Generated by Django 5.2.1 on 2025-06-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_purchase_current_location_purchase_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='coupon_used',
            field=models.CharField(blank=True, help_text='Coupon code used for this purchase', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together={('user', 'coupon')},
        ),
    ]
